version: '3.8'
services:
  postgres:
    image: postgres:latest
    # container_name: postgres-container
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
  redis:
    # container_name: redis-container
    image: redis:latest
  nginx:
    # container_name: nginx-container
    depends_on:
      - api
      - client
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always  
    ports:
      - 3500:80
  api:
    # container_name: api-container
    depends_on:
      - postgres
      - redis
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/server/node_modules
      - ./server:/app/server
    environment:
      - REDIS_HOST=redis
      - PGHOST=postgres
      - REDIS_PORT=6379
      - PGDATABASE=postgres
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGPORT=5432
  client:
    # container_name: client-container
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/client/node_modules
      - ./client:/app/client
  worker:
    # container_name: worker-container
    depends_on: 
      - redis
    build: 
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/worker/node_modules
      - ./worker:/app/worker
    environment:
      - REDIS_HOST=redis
